# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RainDataStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('County', models.CharField(max_length=50)),
                ('Month', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('March', 'March'), ('May', 'May'), ('June', 'June'), ('JUly', 'July'), ('Aug', 'August'), ('sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=25)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
