# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 12:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raindatastore',
            name='Amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator('0')]),
        ),
    ]
