# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160420_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raindatastore',
            name='County',
            field=models.CharField(choices=[('Busia', ' Busia County\n'), ('Bomet', ' Bomet county\n'), ('Nairobi', ' Nairobi County\n'), ('Kisumu', ' Kisumu County\n'), ('Mombasa', ' Mombasa County\n'), ('Baringo', ' Baringo County\n'), ('Marakwet', ' Marakwet county\n'), ('Nandi', '  NandiCounty\n'), ('Kisii', ' Kisii County\n'), ('Kiambu', ' Kiambu County\n'), ("Murang'a", " Murang'a County\n"), ('Nakuru', ' Nakuru County\n')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='raindatastore',
            unique_together=set([('County', 'Month')]),
        ),
    ]
